name: Continuos Training
on: 
  push:
    branches:
      - workflow_ci_cd
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Why to run this?'
        required: false
        default: running CT
jobs:
  Continuos-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Train model
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r src/requirements.txt
          dvc pull model/model.pkl -r model-track
          dvc unprotect model/model.pkl
          dvc repro -f
          echo "Training finished"
          dvc add model/model.pkl -r model-track --to-remote
          dvc push model/model.pkl -r model-track
          echo "model pushed to remote"
      - name: Commit and push changes
        run: |
          git config --global user.email "juanc.barbaran@gmail.com"
          git config --global user.name "Github actions bot"
          git add model/model.pkl.dvc
          git commit -m "Update model"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - uses: iterative/setup-cml@v1
      - name: Publish metrics
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat report.txt >> report.md
          echo '![](./prediction_behavior.png)' >> report.md
          cml comment create --publish report.md

