name: Continuos Integration and Continuos Deployment
on: [push]
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      PROYECT_ID: ${{ secrets.PROYECT_ID }}
      REGION: ${{ secrets.REGION }}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set virtual environment and get model
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install dvc[gs]
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-track
      - name: Auth in gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Set up gcloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: ${{ env.PROYECT_ID }}
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - name: Build and push
        run: |
          docker build . -t $REGISTRY_NAME:$GITHUB_SHA
          gcloud auth configure-docker -q
          sudo -u $USER docker push $REGISTRY_NAME:$GITHUB_SHA
      - name: Deploy to cloudrun
        run: |
          gcloud run services update $SERVICE_NAME --image $REGISTRY_NAME:$GITHUB_SHA --region $REGION