name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Creating and activation virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install dvc[gs]
          pip3 install -r requirements_test.txt
      - name: Run tests
        run: |
          export SERVICE_ACCOUNT_KEY="${{ secrets.SERVICE_ACCOUNT_KEY }}"
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-track
          pytest test.py
